import Head from "next/head";
import AppBar from "../shared/AppBar";
import LandingSection from "./components/LandingSection";
import ComingSoon from "./comingSoon/ComingSoon";
import { getSortedPostsData } from "../utils/module-lession";

export async function getStaticProps() {
  const allPostsData = await getSortedPostsData();
  console.log("app from index", allPostsData);

  return {
    props: {
      allPostsData,
    },
  };
}


export default function Home() {



  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        {/* <link href="/dist/output.css" rel="stylesheet"/> */}
      </Head>
      <div className='w-full'>
        <LandingSection />
        {/* <ComingSoon/>  */}
      </div>
    </>
  );
}
